Repository AY2122S2-CS2103T-W11-1/tp, pull requests merged in 2022-04, with the labels that each got.

#142 Fix issues
  docs/UserGuide.md
  docs/team/fredtwt.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CancelEventCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/Information.java
  src/main/java/seedu/address/model/person/Cca.java
  src/main/java/seedu/address/model/person/Education.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Internship.java
  src/main/java/seedu/address/model/person/Module.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Story

#157 Branch testcase
  docs/team/fredtwt.md
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/Information.java
  src/test/java/seedu/address/logic/commands/EventCommandTest.java
Labels: test case

#158 Test cases done for event field types
  src/test/java/seedu/address/logic/commands/CancelEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/event/DateTimeTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/InformationTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: test case

#159 Test cases for JsonAdaptedName
  README.md
  docs/DeveloperGuide.md
  docs/team/ongkimlai.md
  src/main/java/seedu/address/storage/JsonAdaptedName.java
  src/test/java/seedu/address/storage/JsonAdaptedNameTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: test case

#162 Enlarge RemoveTagSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/RemoveTagState1.puml
  docs/images/RemoveTagState1.png
  docs/team/ongkimlai.md
Labels: documentation

#163 Separate RemoveTagSequenceDiagram into parse and execute
  docs/DeveloperGuide.md
  docs/diagrams/RemoveTagSequenceDiagram0.puml
  docs/diagrams/RemoveTagSequenceDiagram1.puml
  docs/images/RemoveTagSequenceDiagram0.png
  docs/images/RemoveTagSequenceDiagram1.png
Labels: documentation

#164 Separate DeleteMultipleSequenceDiagram into parse and execute
  docs/DeveloperGuide.md
  docs/diagrams/DeleteMultipleSequenceDiagram0.puml
  docs/diagrams/DeleteMultipleSequenceDiagram1.puml
  docs/images/DeleteMultipleSequenceDiagram0.png
  docs/images/DeleteMultipleSequenceDiagram1.png
Labels: documentation

#165 Fix error in DeleteMultipleSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteMultipleSequenceDiagram0.puml
  docs/diagrams/DeleteMultipleSequenceDiagram1.puml
  docs/images/DeleteMultipleSequenceDiagram0.png
  docs/images/DeleteMultipleSequenceDiagram1.png
Labels: documentation

#167 Change sequence diagram for Tag, Event & CancelEvent
  docs/DeveloperGuide.md
  docs/diagrams/CancelEventSequenceDiagram0.puml
  docs/diagrams/CancelEventSequenceDiagram1.puml
  docs/diagrams/EventSequenceDiagram0.puml
  docs/diagrams/EventSequenceDiagram1.puml
  docs/diagrams/TagSequenceDiagram0.puml
  docs/diagrams/TagSequenceDiagram1.puml
  docs/images/CancelEventSequenceDiagram0.png
  docs/images/CancelEventSequenceDiagram1.png
  docs/images/EventSequenceDiagram0.png
  docs/images/EventSequenceDiagram1.png
  docs/images/TagSequenceDiagram0.png
  docs/images/TagSequenceDiagram1.png
Labels: documentation

#168 Add return arrow from LogicManager in various Sequence Diagram
  docs/diagrams/CancelEventSequenceDiagram0.puml
  docs/diagrams/DeleteMultipleSequenceDiagram0.puml
  docs/diagrams/EventSequenceDiagram0.puml
  docs/diagrams/RemoveTagSequenceDiagram0.puml
  docs/diagrams/TagSequenceDiagram0.puml
  docs/images/CancelEventSequenceDiagram0.png
  docs/images/EventSequenceDiagram0.png
  docs/images/RemoveTagSequenceDiagram0.png
  docs/images/TagSequenceDiagram0.png
Labels: documentation

#169 Update DG
  docs/DeveloperGuide.md
  docs/team/fredtwt.md
Labels: documentation

#170 Fix EditCommandTest and EditCommandParserTest
  docs/AboutUs.md
  docs/team/fredtwt.md
  docs/team/ongkimlai.md
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: test case

#171 Add manual testing instructions
  docs/DeveloperGuide.md
Labels: documentation

#166 Find uml diagram
  docs/DeveloperGuide.md
  docs/diagrams/FindClassDiagram.puml
  docs/images/FindClassDiagram.png
  docs/team/viki0526.md
Labels: documentation

#172 Add documentation
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram0.puml
  docs/diagrams/FindPredicatesClassDiagram.puml
  docs/images/EditSequenceDiagram0.png
  docs/images/FindPredicatesClassDiagram.png
  docs/team/fredtwt.md
  docs/team/manu2002g.md
  docs/team/viki0526.md
Labels: documentation

#173 Update fredtwt.md
  docs/team/fredtwt.md
Labels: documentation

#174 Update DG UG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ongkimlai.md
Labels: documentation

#175 Add page breaks to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ongkimlai.md
Labels: documentation

#176 Add Test code + Update PPP
  docs/team/manu2002g.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ShowEventsCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowEventsCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShowEventsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShowEventsCommandTest.java
Labels: documentation, test case

#177 Add more page breaks for DG formatting
  docs/DeveloperGuide.md
Labels: documentation

#178 Update PPP and add DG page breaks
  docs/DeveloperGuide.md
  docs/team/ongkimlai.md
Labels: documentation

#180 Update DG
  docs/DeveloperGuide.md
  docs/team/fredtwt.md
  docs/team/ongkimlai.md
Labels: documentation

#181 Update fredtwt.md
  docs/team/fredtwt.md
Labels: documentation
