Repository AY2122S2-CS2103T-W11-1/tp, pull requests merged in 2022-03, with the labels that each got.

#20 Add manu2002g.md and update AboutUs.md
  docs/AboutUs.md
  docs/team/manu2002g.md
Labels: documentation

#22 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/team/viki0526.md
Labels: documentation

#25 Add mock UI
  docs/images/Ui.png
Labels: documentation

#32 Amend UserGuide.md
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#33 Remove tagging functionality in AddCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#34 Added delete multiple contacts functionality into DeleteCommand
  docs/UserGuide.md
  docs/team/ongkimlai.md
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Story

#35 Add tag feature
  docs/UserGuide.md
  docs/team/fredtwt.md
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/person/Cca.java
  src/main/java/seedu/address/model/person/Education.java
  src/main/java/seedu/address/model/person/Internship.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#37 Amend tag command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/person/Cca.java
  src/main/java/seedu/address/model/person/Education.java
  src/main/java/seedu/address/model/person/Internship.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#39 Model & Storage: Add test cases for Tag Command
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Cca.java
  src/main/java/seedu/address/model/person/Education.java
  src/main/java/seedu/address/model/person/Internship.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/CcaTest.java
  src/test/java/seedu/address/model/person/EducationTest.java
  src/test/java/seedu/address/model/person/InternshipTest.java
  src/test/java/seedu/address/model/person/ModuleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#42 Branch edit command v1.2
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Module.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Story

#41 Tag command testing
  docs/team/ongkimlai.md
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Story

#44 Add find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindAndPredicateParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindOrPredicateParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Story

#51 Viki0526 Find contacts using Tags
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/FindAndPredicateParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindOrPredicateParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Cca.java
  src/main/java/seedu/address/model/person/CcaContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/CcaContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Education.java
  src/main/java/seedu/address/model/person/EducationContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/EducationContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Internship.java
  src/main/java/seedu/address/model/person/InternshipContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/InternshipContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/Module.java
  src/main/java/seedu/address/model/person/ModuleContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/ModuleContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/TagComponent.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/ui/TagComponentTest.java
Labels: type.Story

#52 Removetag v1.2b
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ongkimlai.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#54 Fix find parser
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ongkimlai.md
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug, type.Story

#56 Update UI
  docs/team/ongkimlai.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCardComponent.java
  src/main/java/seedu/address/ui/TagComponent.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/ui/TagComponentTest.java
Labels: type.Story

#61 Sorting person
  build.gradle
  docs/UserGuide.md
  docs/images/find-sShopeeCS2040sCS2030s.png
  docs/images/findShopeeCS2040sCS2030sResult.png
  docs/images/help_message.png
  docs/team/ongkimlai.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Story

#64 Branch event command
  docs/UserGuide.md
  docs/team/fredtwt.md
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/Information.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedName.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Story

#65 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/TagClassDiagram.puml
  docs/diagrams/TagSequenceDiagram.puml
  docs/images/TagClassDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
Labels: documentation

#66 Update dg
  docs/DeveloperGuide.md
Labels: documentation

#68 DG update for Find Command
  docs/DeveloperGuide.md
Labels: documentation

#69 Update DG for Edit command
  docs/DeveloperGuide.md
Labels: documentation

#67 Add design details for Tag feature in DG
  docs/DeveloperGuide.md
  docs/diagrams/TagSequenceDiagram.puml
  docs/images/TagSequenceDiagram.png
Labels: documentation

#70 Add working events panel
  docs/DeveloperGuide.md
  docs/team/ongkimlai.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/EventCardComponent.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCardComponent.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Story

#72 Events UI
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/EventCardComponent.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Story

#73 Handle delete dependency for Eventcommand
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/event/Event.java
Labels: type.Story

#75 Add Predicates for upcoming and past events in Model.java
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
Labels: type.Story

#76 Add CancelEventCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CancelEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CancelEventCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Story

#79 Events UI
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/EventCardComponent.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Story

#80 Viki0526 Find event
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindEventPredicateParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/event/DateTimePredicate.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventFieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/EventInfoContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/EventNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/EventParticipantsContainsKeywordsPredicate.java
Labels: documentation, type.Story

#81 Fix edit command bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug

#82 Add edit dependency on EventCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/resources/view/EventListPanel.fxml
Labels: type.Story

#83 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/team/fredtwt.md
  docs/team/ongkimlai.md
Labels: documentation

#84 Fix bug in Find command + Add new Functionality
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindAndPredicateParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindOrPredicateParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicateOr.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: bug, type.Story

#85 Fix resizing issues with stackpanes
  docs/team/ongkimlai.md
  src/main/resources/view/MainWindow.fxml
Labels: bug

#86 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/RemoveTagSequenceDiagram.puml
  docs/diagrams/TagSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/RemoveTagSequenceDiagram.png
  docs/images/TagSequenceDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
Labels: documentation

#87 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/EventClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/EventClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/team/fredtwt.md
Labels: documentation

#88 Update EventCommand design details in DG
  docs/DeveloperGuide.md
  docs/diagrams/EventSequenceDiagram.puml
  docs/images/EventSequenceDiagram.png
  docs/team/fredtwt.md
Labels: documentation

#89 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiSampleAddressBook.png
  docs/team/ongkimlai.md
Labels: documentation

#90 Update design details for cancelevent in DG
  docs/DeveloperGuide.md
  docs/diagrams/CancelEventSequenceDiagram.puml
  docs/images/CancelEventSequenceDiagram.png
Labels: documentation

#91 Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation

#93 Add showevents command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ShowEventsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ShowEventsCommandParser.java
Labels: type.Story

#92 Find command fix
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/EventFieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/EventParticipantsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicateOr.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: bug

#94 Remove view preparations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ShowEventsCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#95 Reformat DG and update FindCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CancelEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventFieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/EventParticipantsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicateOr.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicateAnd.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicateOr.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: bug, documentation

#96 Fix EventCommand
  docs/team/fredtwt.md
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
Labels: bug

#97 Clean up code and update UG with constraints
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ongkimlai.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: documentation

#98 Before and after screenshots added to UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiSampleAddressBook.png
  docs/images/find-sShopeeCS2040sCS2030s.png
  docs/images/findShopeeCS2040sCS2030sResult.png
  docs/images/screenshots/addAlissonBecker.png
  docs/images/screenshots/beforeCommand.png
  docs/images/screenshots/eventMovieMarathon.png
  docs/images/screenshots/find-sShopeeCS2040sCS2030s.png
  docs/images/screenshots/findAlexDavidResult.png
  docs/images/screenshots/findShopeeCS2040sCS2030sResult.png
  docs/images/screenshots/tagInternshipModuleModule.png
  docs/team/ongkimlai.md
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: documentation

#99 Fix formatting errors in UG
  docs/UserGuide.md
Labels: documentation

#100 Fix formatting errors in Invalid Examples box
  docs/UserGuide.md
Labels: documentation

#101 Change div markdown to block
  docs/UserGuide.md
Labels: documentation

#102 Change Display UI and toString methods of events/persons
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CancelEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/model/person/Person.java
Labels: enhancement

#103 Updated screenshots for new result messages
  docs/UserGuide.md
  docs/images/screenshots/addAlissonBecker.png
  docs/images/screenshots/beforeCommand.png
  docs/images/screenshots/find-sShopeeCS2040sCS2030s.png
  docs/images/screenshots/findShopeeCS2040sCS2030sResult.png
  docs/images/screenshots/tagInternshipModuleModule.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: documentation
